import type { Metadata } from 'next';
import { openSans } from '@/components/ui/fonts';
import '@/styles/globals.css';
import Navbar from '@/components/navbar/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${openSans.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
